### ISSUE TITLE
setup error

### ISSUE THREAD

**Issue by cguetot** [semiller10/postnovo#1]
Hi, 

I would like to test postnovo but I got an error message while I try to set up it. Actually, the same error for all command lines, e.g, `python main.py setup --deepnovo_low --deepnovo_high --container /path/container` or ´python main.py setup --check_updates` 

`> python3 main.py setup --deepnovo_low --deepnovo_high --container /mnt/DATA_DISKS/WORKSPACE2/cguetot/installers/postnovo/tensorflow.simg`
Traceback (most recent call last):
  File "main.py", line 12, in <module>
    import interspec
  File "/mnt/DATA_DISKS/WORKSPACE2/cguetot/installers/postnovo/postnovo/interspec.py", line 100
    global cluster_dfs
    ^
SyntaxError: name 'cluster_dfs' is used prior to global declaration

or 

` > python3 main.py setup --check_update`
Traceback (most recent call last):
  File "main.py", line 12, in <module>
    import interspec
  File "/mnt/DATA_DISKS/WORKSPACE2/cguetot/installers/postnovo/postnovo/interspec.py", line 100
    global cluster_dfs
    ^
SyntaxError: name 'cluster_dfs' is used prior to global declaration

I tried with version 1.0.9-alpha and also from the master branch.

thank you in advance,

Carlos

**Comment by bdartigues** [comment]
you need. to comment theses lines in each files. this way it works !
